### ISSUE TITLE
Review IHO document model for correctness

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-iho#1]

**Comment by opoudjis** [comment]
There's only one IHO Committee: is that right? Is it there to be extensible in the future?

I assume the document type abbreviations are going to come up in document identifiers?

Nothing else of note...

**Comment by ronaldtse** [comment]
> There's only one IHO Committee: is that right? Is it there to be extensible in the future?

Just received clarification there are 2. 

I will update the model with new information I've received.
