### ISSUE TITLE
Handle S-52 document relationships and editions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-iho#2]
We have to ensure that these document relationships and editions can be handled by the IHO model.

<img width="816" alt="Screen Shot 2020-04-01 at 1 55 25 AM" src="https://user-images.githubusercontent.com/11865/78059084-dbaf5180-73bb-11ea-9928-af1bf7dff981.png">

**Comment by opoudjis** [comment]
I have no idea what you are asking for here.

These are successive updates of editions, with "clarifications" resulting in a document version which has not been given a distinct edition. Editions being updates of other editions with dates is already done in relaton. Random change notes is not done in relaton, and should not be.

What am I missing here?

**Comment by ronaldtse** [comment]
Originally I was meaning to model the relationship (old document + amendment => new document). But this is a generic issue and there is nothing specific in this ticket. Closing.
